# basic options
title: thatbloggerguy
author: PavlosDnds
email: pavlosdnds@gmail.com
description: An everyday blog
twitter_username: BartoBartolomeo
github_username:  Pavlosdnds

# Build settings
markdown: kramdown
theme: minima
